# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: portData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='portData.proto',
  package='p',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eportData.proto\x12\x01p\"5\n\rportDataFrame\x12$\n\x08\x65xamples\x18\x01 \x03(\x0b\x32\x12.p.portScanExample\"\xd7\x05\n\x0fportScanExample\x12\x17\n\x0f\x66rame_info_time\x18\x01 \x01(\x02\x12\x1d\n\x15\x66rame_info_time_epoch\x18\x02 \x01(\x02\x12\x19\n\x11\x66rame_info_number\x18\x03 \x01(\x02\x12\x16\n\x0e\x66rame_info_len\x18\x04 \x01(\x02\x12\x1a\n\x12\x66rame_info_cap_len\x18\x05 \x01(\x02\x12\r\n\x05ip_id\x18\x06 \x01(\x03\x12\x10\n\x08ip_flags\x18\x07 \x01(\x03\x12\x13\n\x0bip_flags_df\x18\x08 \x01(\x02\x12\x0e\n\x06ip_ttl\x18\t \x01(\x02\x12\x13\n\x0bip_checksum\x18\n \x01(\x03\x12\x0e\n\x06ip_src\x18\x0b \x01(\t\x12\x0e\n\x06ip_dst\x18\x0c \x01(\t\x12\x0e\n\x06ip_len\x18\r \x01(\x02\x12\x12\n\nip_dsfield\x18\x0e \x01(\x03\x12\x13\n\x0btcp_srcport\x18\x0f \x01(\x02\x12\x13\n\x0btcp_dstport\x18\x10 \x01(\x02\x12\x0f\n\x07tcp_seq\x18\x11 \x01(\x02\x12\x0f\n\x07tcp_ack\x18\x12 \x01(\x02\x12\x0f\n\x07tcp_len\x18\x14 \x01(\x02\x12\x13\n\x0btcp_hdr_len\x18\x15 \x01(\x02\x12\x11\n\ttcp_flags\x18\x16 \x01(\x03\x12\x15\n\rtcp_flags_fin\x18\x17 \x01(\x02\x12\x15\n\rtcp_flags_syn\x18\x18 \x01(\x02\x12\x17\n\x0ftcp_flags_reset\x18\x19 \x01(\x02\x12\x16\n\x0etcp_flags_push\x18\x1a \x01(\x02\x12\x15\n\rtcp_flags_ack\x18\x1b \x01(\x02\x12\x15\n\rtcp_flags_urg\x18\x1c \x01(\x02\x12\x15\n\rtcp_flags_cwr\x18\x1d \x01(\x02\x12\x17\n\x0ftcp_window_size\x18\x1e \x01(\x02\x12\x14\n\x0ctcp_checksum\x18\x1f \x01(\x03\x12\x1a\n\x12tcp_urgent_pointer\x18  \x01(\x02\x12\x1b\n\x13tcp_options_mss_val\x18! \x01(\x02\x12\r\n\x05label\x18\" \x01(\x03\x62\x06proto3'
)




_PORTDATAFRAME = _descriptor.Descriptor(
  name='portDataFrame',
  full_name='p.portDataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='examples', full_name='p.portDataFrame.examples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=74,
)


_PORTSCANEXAMPLE = _descriptor.Descriptor(
  name='portScanExample',
  full_name='p.portScanExample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_info_time', full_name='p.portScanExample.frame_info_time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_info_time_epoch', full_name='p.portScanExample.frame_info_time_epoch', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_info_number', full_name='p.portScanExample.frame_info_number', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_info_len', full_name='p.portScanExample.frame_info_len', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_info_cap_len', full_name='p.portScanExample.frame_info_cap_len', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_id', full_name='p.portScanExample.ip_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_flags', full_name='p.portScanExample.ip_flags', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_flags_df', full_name='p.portScanExample.ip_flags_df', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_ttl', full_name='p.portScanExample.ip_ttl', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_checksum', full_name='p.portScanExample.ip_checksum', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_src', full_name='p.portScanExample.ip_src', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_dst', full_name='p.portScanExample.ip_dst', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_len', full_name='p.portScanExample.ip_len', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_dsfield', full_name='p.portScanExample.ip_dsfield', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_srcport', full_name='p.portScanExample.tcp_srcport', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_dstport', full_name='p.portScanExample.tcp_dstport', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_seq', full_name='p.portScanExample.tcp_seq', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_ack', full_name='p.portScanExample.tcp_ack', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_len', full_name='p.portScanExample.tcp_len', index=18,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_hdr_len', full_name='p.portScanExample.tcp_hdr_len', index=19,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags', full_name='p.portScanExample.tcp_flags', index=20,
      number=22, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags_fin', full_name='p.portScanExample.tcp_flags_fin', index=21,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags_syn', full_name='p.portScanExample.tcp_flags_syn', index=22,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags_reset', full_name='p.portScanExample.tcp_flags_reset', index=23,
      number=25, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags_push', full_name='p.portScanExample.tcp_flags_push', index=24,
      number=26, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags_ack', full_name='p.portScanExample.tcp_flags_ack', index=25,
      number=27, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags_urg', full_name='p.portScanExample.tcp_flags_urg', index=26,
      number=28, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_flags_cwr', full_name='p.portScanExample.tcp_flags_cwr', index=27,
      number=29, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_window_size', full_name='p.portScanExample.tcp_window_size', index=28,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_checksum', full_name='p.portScanExample.tcp_checksum', index=29,
      number=31, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_urgent_pointer', full_name='p.portScanExample.tcp_urgent_pointer', index=30,
      number=32, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcp_options_mss_val', full_name='p.portScanExample.tcp_options_mss_val', index=31,
      number=33, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='p.portScanExample.label', index=32,
      number=34, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=804,
)

_PORTDATAFRAME.fields_by_name['examples'].message_type = _PORTSCANEXAMPLE
DESCRIPTOR.message_types_by_name['portDataFrame'] = _PORTDATAFRAME
DESCRIPTOR.message_types_by_name['portScanExample'] = _PORTSCANEXAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

portDataFrame = _reflection.GeneratedProtocolMessageType('portDataFrame', (_message.Message,), {
  'DESCRIPTOR' : _PORTDATAFRAME,
  '__module__' : 'portData_pb2'
  # @@protoc_insertion_point(class_scope:p.portDataFrame)
  })
_sym_db.RegisterMessage(portDataFrame)

portScanExample = _reflection.GeneratedProtocolMessageType('portScanExample', (_message.Message,), {
  'DESCRIPTOR' : _PORTSCANEXAMPLE,
  '__module__' : 'portData_pb2'
  # @@protoc_insertion_point(class_scope:p.portScanExample)
  })
_sym_db.RegisterMessage(portScanExample)


# @@protoc_insertion_point(module_scope)
